// ===================== FAKE DATA =====================

export const sexlarData = [
  {
    id: "SEX-07",
    nom: "ЛПК",
    emoji: "🔩",
    uchastkalar: 6,
    uskunalar: 30,
    faolUskunalar: 30,
    holat: "faol",
    yuk: 90,
    harorat: 24,
    ishchilar: 120,
    smena: "—",
    xavf: "past",
  },
  {
    id: "SEX-02",
    nom: "СПП",
    emoji: "⚙️",
    uchastkalar: 5,
    uskunalar: 7,
    faolUskunalar: 6,
    holat: "faol",
    yuk: 76,
    harorat: 1620,
    ishchilar: 18,
    smena: "II",
    xavf: "past",
  },
  {
    id: "SEX-03",
    nom: "ШПП",
    emoji: "⚡",
    uchastkalar: 3,
    uskunalar: 6,
    faolUskunalar: 5,
    holat: "ogohlantirish",
    yuk: 95,
    harorat: 1380,
    ishchilar: 15,
    smena: "II",
    xavf: "orta",
  },
  {
    id: "SEX-04",
    nom: "ЭСПП",
    emoji: "🔄",
    uchastkalar: 6,
    uskunalar: 10,
    faolUskunalar: 10,
    holat: "faol",
    yuk: 62,
    harorat: 920,
    ishchilar: 32,
    smena: "II",
    xavf: "past",
  },

  {
    id: "SEX-05",
    nom: "КОПРОВЫЙ",
    emoji: "🏗️",
    uchastkalar: 3,
    uskunalar: 6,
    faolUskunalar: 4,
    holat: "xato",
    yuk: 45,
    harorat: 780,
    ishchilar: 12,
    smena: "II",
    xavf: "yuqori",
  },
  {
    id: "SEX-06",
    nom: "ППФ",
    emoji: "🔩",
    uchastkalar: 3,
    uskunalar: 5,
    faolUskunalar: 0,
    holat: "toxtagan",
    yuk: 0,
    harorat: 24,
    ishchilar: 0,
    smena: "—",
    xavf: "past",
  },
  {
    id: "SEX-09",
    nom: "ПЦМ",
    emoji: "🧪",
    uchastkalar: 5,
    uskunalar: 18,
    faolUskunalar: 16,
    holat: "faol",
    yuk: 84,
    harorat: 980,
    ishchilar: 54,
    smena: "II",
    xavf: "yuqori",
  },
  {
    id: "SEX-01",
    nom: "ПТИМ",
    emoji: "🔥",
    uchastkalar: 4,
    uskunalar: 8,
    faolUskunalar: 8,
    holat: "faol",
    yuk: 88,
    harorat: 1480,
    ishchilar: 24,
    smena: "II",
    xavf: "past",
  },

  {
    id: "SEX-08",
    nom: "ПТНП",
    emoji: "🎨",
    uchastkalar: 4,
    uskunalar: 12,
    faolUskunalar: 10,
    holat: "faol",
    yuk: 72,
    harorat: 180,
    ishchilar: 36,
    smena: "II",
    xavf: "orta",
  },
];

export const uchastkalarData = [
  {
    id: "UCH-01A",
    nom: "Участок штамповки",
    sexId: "SEX-01",
    holat: "faol",
    uskunalar: 3,
    ishchilar: 6,
    harorat: 1480,
    bosim: 4.2,
    samaradorlik: 94,
  },
  {
    id: "UCH-01B",
    nom: "Участок РИО и РММ",
    sexId: "SEX-01",
    holat: "faol",
    uskunalar: 4,
    ishchilar: 8,
    harorat: 1350,
    bosim: 3.8,
    samaradorlik: 88,
  },
  {
    id: "UCH-01C",
    nom: "Участок мокрый помола",
    sexId: "SEX-01",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 4,
    harorat: 1250,
    bosim: 2.1,
    samaradorlik: 91,
  },
  {
    id: "UCH-01D",
    nom: "Участок травильный",
    sexId: "SEX-01",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 3,
    harorat: 420,
    bosim: 1.2,
    samaradorlik: 97,
  },
  {
    id: "UCH-02A",
    nom: "Участок стана и печей",
    sexId: "SEX-02",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 5,
    harorat: 1620,
    bosim: 5.4,
    samaradorlik: 82,
  },
  {
    id: "UCH-02B",
    nom: "Участок по ревизии кассет и ножниц стана",
    sexId: "SEX-02",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 5,
    harorat: 1590,
    bosim: 5.1,
    samaradorlik: 86,
  },
  {
    id: "UCH-02C",
    nom: "Участок адъюстажа и холодильника стана",
    sexId: "SEX-02",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 4,
    harorat: 1480,
    bosim: 4.8,
    samaradorlik: 79,
  },
  {
    id: "UCH-02D",
    nom: "Участок линия по производству катанки",
    sexId: "SEX-02",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 3,
    harorat: 280,
    bosim: 1.5,
    samaradorlik: 95,
  },
  {
    id: "UCH-02E",
    nom: "Другие (АБК, столовая, душевая, сан-узлы)",
    sexId: "SEX-02",
    holat: "ogohlantirish",
    uskunalar: 2,
    ishchilar: 2,
    harorat: 340,
    bosim: 8.3,
    samaradorlik: 71,
  },
  {
    id: "UCH-03A",
    nom: "Участок печей и шаропрокатный стан",
    sexId: "SEX-03",
    holat: "ogohlantirish",
    uskunalar: 2,
    ishchilar: 5,
    harorat: 1380,
    bosim: 3.9,
    samaradorlik: 68,
  },
  {
    id: "UCH-03B",
    nom: "Участок подъемно-транспортного оборудования",
    sexId: "SEX-03",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 6,
    harorat: 1290,
    bosim: 3.2,
    samaradorlik: 85,
  },
  {
    id: "UCH-03C",
    nom: "Другие (АБК)",
    sexId: "SEX-03",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 4,
    harorat: 45,
    bosim: 0.0,
    samaradorlik: 99,
  },
  {
    id: "UCH-04A",
    nom: "Участок печей",
    sexId: "SEX-04",
    holat: "faol",
    uskunalar: 4,
    ishchilar: 10,
    harorat: 920,
    bosim: 2.8,
    samaradorlik: 92,
  },
  {
    id: "UCH-04B",
    nom: "Машина непрерывного литья заготовок №1",
    sexId: "SEX-04",
    holat: "faol",
    uskunalar: 3,
    ishchilar: 8,
    harorat: 880,
    bosim: 2.6,
    samaradorlik: 88,
  },
  {
    id: "UCH-04C",
    nom: "Участок газоочистки",
    sexId: "SEX-04",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 6,
    harorat: 240,
    bosim: 1.4,
    samaradorlik: 96,
  },
  {
    id: "UCH-04D",
    nom: "Участок ИОУ (известково-обжигового участка)",
    sexId: "SEX-04",
    holat: "faol",
    uskunalar: 3,
    ishchilar: 6,
    harorat: 120,
    bosim: 0.8,
    samaradorlik: 94,
  },
  {
    id: "UCH-04E",
    nom: "Другие (АБК, столовая, душевая, сан-узлы)",
    sexId: "SEX-04",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 4,
    harorat: 35,
    bosim: 0.2,
    samaradorlik: 98,
  },
  {
    id: "UCH-04F",
    nom: "Участок подъемно-транспортного оборудования",
    sexId: "SEX-04",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 4,
    harorat: 22,
    bosim: 0.0,
    samaradorlik: 100,
  },
  {
    id: "UCH-05A",
    nom: "АБК (другие)",
    sexId: "SEX-05",
    holat: "xato",
    uskunalar: 2,
    ishchilar: 4,
    harorat: 780,
    bosim: 6.1,
    samaradorlik: 0,
  },
  {
    id: "UCH-05B",
    nom: "Участка копер",
    sexId: "SEX-05",
    holat: "faol",
    uskunalar: 3,
    ishchilar: 5,
    harorat: 420,
    bosim: 2.2,
    samaradorlik: 78,
  },
  {
    id: "UCH-05C",
    nom: "Эстакада 3",
    sexId: "SEX-05",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 3,
    harorat: 28,
    bosim: 0.0,
    samaradorlik: 100,
  },
  {
    id: "UCH-06A",
    nom: "Печной участок",
    sexId: "SEX-06",
    holat: "toxtagan",
    uskunalar: 2,
    ishchilar: 0,
    harorat: 22,
    bosim: 0.0,
    samaradorlik: 0,
  },
  {
    id: "UCH-06B",
    nom: "Участок подъемно",
    sexId: "SEX-06",
    holat: "toxtagan",
    uskunalar: 2,
    ishchilar: 0,
    harorat: 22,
    bosim: 0.0,
    samaradorlik: 0,
  },
  {
    id: "UCH-06C",
    nom: "транспортного оборудования",
    sexId: "SEX-06",
    holat: "toxtagan",
    uskunalar: 2,
    ishchilar: 0,
    harorat: 22,
    bosim: 0.0,
    samaradorlik: 0,
  },
  {
    id: "UCH-07A",
    nom: "Zagotovka qabul qilish va transport uchastkasi",
    sexId: "SEX-07",
    holat: "faol",
    uskunalar: 4,
    ishchilar: 120,
    harorat: 28,
    bosim: 0,
    samaradorlik: 0,
  },
  {
    id: "UCH-07B",
    nom: "Qizdirish pechlari uchastkasi",
    sexId: "SEX-07",
    holat: "faol",
    uskunalar: 3,
    ishchilar: 60,
    harorat: 1200,
    bosim: 2.5,
    samaradorlik: 0,
  },
  {
    id: "UCH-07C",
    nom: "Qora prokatlash stani (Roughing Mill)",
    sexId: "SEX-07",
    holat: "faol",
    uskunalar: 4,
    ishchilar: 85,
    harorat: 1050,
    bosim: 3.2,
    samaradorlik: 0,
  },
  {
    id: "UCH-07D",
    nom: "Toza prokatlash stani (Finishing Mill)",
    sexId: "SEX-07",
    holat: "faol",
    uskunalar: 3,
    ishchilar: 90,
    harorat: 980,
    bosim: 2.6,
    samaradorlik: 0,
  },
  {
    id: "UCH-07E",
    nom: "Sovitish stoli va tekislash",
    sexId: "SEX-07",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 123,
    harorat: 120,
    bosim: 1.1,
    samaradorlik: 0,
  },
  {
    id: "UCH-07F",
    nom: "Kesish va tayyor mahsulot",
    sexId: "SEX-07",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 76,
    harorat: 35,
    bosim: 0.4,
    samaradorlik: 0,
  },
  {
    id: "UCH-08A",
    nom: "Sirtni tayyorlash (tozalash)",
    sexId: "SEX-08",
    holat: "faol",
    uskunalar: 3,
    ishchilar: 8,
    harorat: 40,
    bosim: 1.2,
    samaradorlik: 88,
  },
  {
    id: "UCH-08B",
    nom: "Gruntlash (primer)",
    sexId: "SEX-08",
    holat: "faol",
    uskunalar: 3,
    ishchilar: 10,
    harorat: 90,
    bosim: 1.8,
    samaradorlik: 82,
  },
  {
    id: "UCH-08C",
    nom: "Emal qoplash liniyasi",
    sexId: "SEX-08",
    holat: "ogohlantirish",
    uskunalar: 4,
    ishchilar: 12,
    harorat: 160,
    bosim: 2.4,
    samaradorlik: 76,
  },
  {
    id: "UCH-08D",
    nom: "Quritish pechlari",
    sexId: "SEX-08",
    holat: "faol",
    uskunalar: 2,
    ishchilar: 6,
    harorat: 180,
    bosim: 2.0,
    samaradorlik: 85,
  },
  {
    id: "UCH-09A",
    nom: "Xomashyo tayyorlash (mis, alyuminiy)",
    sexId: "SEX-09",
    holat: "faol",
    uskunalar: 3,
    ishchilar: 10,
    harorat: 120,
    bosim: 1.5,
    samaradorlik: 87,
  },
  {
    id: "UCH-09B",
    nom: "Eritish pechlari (induksion)",
    sexId: "SEX-09",
    holat: "faol",
    uskunalar: 4,
    ishchilar: 12,
    harorat: 980,
    bosim: 2.8,
    samaradorlik: 82,
  },
  {
    id: "UCH-09C",
    nom: "Quyish (litiy) liniyasi",
    sexId: "SEX-09",
    holat: "ogohlantirish",
    uskunalar: 4,
    ishchilar: 11,
    harorat: 860,
    bosim: 2.2,
    samaradorlik: 74,
  },
  {
    id: "UCH-09D",
    nom: "Prokatlash va shakllantirish",
    sexId: "SEX-09",
    holat: "faol",
    uskunalar: 4,
    ishchilar: 13,
    harorat: 420,
    bosim: 1.9,
    samaradorlik: 89,
  },
  {
    id: "UCH-09E",
    nom: "Sovutish va sifat nazorati",
    sexId: "SEX-09",
    holat: "faol",
    uskunalar: 3,
    ishchilar: 8,
    harorat: 80,
    bosim: 0.8,
    samaradorlik: 93,
  },
];

export const uskunalarData = [
  {
    id: "USK-001",
    nom: "Domna Pechi №1",
    tur: "Pech",
    sexId: "SEX-01",
    uchastkId: "UCH-01A",
    holat: "faol",
    samaradorlik: 94,
    harorat: 1480,
    bosim: 4.2,
    quvvat: 1200,
    ishVaqti: 4820,
    keyingiTA: 180,
    model: "BF-2400X",
    ishlab: "2018",
    imgUrl: "/images/uskunalar/domna-pech.svg",
  },
  {
    id: "USK-002",
    nom: "Domna Pechi №2",
    tur: "Pech",
    sexId: "SEX-01",
    uchastkId: "UCH-01A",
    holat: "faol",
    samaradorlik: 91,
    harorat: 1450,
    bosim: 4.0,
    quvvat: 1180,
    ishVaqti: 3940,
    keyingiTA: 60,
    model: "BF-2400X",
    ishlab: "2019",
    imgUrl: "/images/uskunalar/domna-pech.svg",
  },
  {
    id: "USK-003",
    nom: "Konverter №1",
    tur: "Konverter",
    sexId: "SEX-02",
    uchastkId: "UCH-02A",
    holat: "faol",
    samaradorlik: 86,
    harorat: 1620,
    bosim: 5.4,
    quvvat: 840,
    ishVaqti: 6200,
    keyingiTA: 30,
    model: "LD-300T",
    ishlab: "2016",
    imgUrl: "/images/uskunalar/konverter.svg",
  },
  {
    id: "USK-004",
    nom: "Konverter №2",
    tur: "Konverter",
    sexId: "SEX-02",
    uchastkId: "UCH-02B",
    holat: "faol",
    samaradorlik: 82,
    harorat: 1590,
    bosim: 5.1,
    quvvat: 810,
    ishVaqti: 5840,
    keyingiTA: 90,
    model: "LD-300T",
    ishlab: "2016",
    imgUrl: "/images/uskunalar/konverter.svg",
  },
  {
    id: "USK-005",
    nom: "Elektr Pech №1",
    tur: "Elektr Pech",
    sexId: "SEX-03",
    uchastkId: "UCH-03B",
    holat: "faol",
    samaradorlik: 85,
    harorat: 1290,
    bosim: 3.2,
    quvvat: 420,
    ishVaqti: 3100,
    keyingiTA: 45,
    model: "EAF-120",
    ishlab: "2020",
    imgUrl: "/images/uskunalar/elektr-pech.svg",
  },
  {
    id: "USK-006",
    nom: "Elektr Pech №2",
    tur: "Elektr Pech",
    sexId: "SEX-03",
    uchastkId: "UCH-03A",
    holat: "ogohlantirish",
    samaradorlik: 68,
    harorat: 1380,
    bosim: 3.9,
    quvvat: 400,
    ishVaqti: 2940,
    keyingiTA: 15,
    model: "EAF-120",
    ishlab: "2020",
    imgUrl: "/images/uskunalar/elektr-pech.svg",
  },
  {
    id: "USK-007",
    nom: "Prokatchi №1",
    tur: "Prokat",
    sexId: "SEX-04",
    uchastkId: "UCH-04A",
    holat: "faol",
    samaradorlik: 92,
    harorat: 920,
    bosim: 2.8,
    quvvat: 560,
    ishVaqti: 7200,
    keyingiTA: 120,
    model: "RM-650H",
    ishlab: "2015",
    imgUrl: "/images/uskunalar/prokat.svg",
  },
  {
    id: "USK-008",
    nom: "Prokatchi №2",
    tur: "Prokat",
    sexId: "SEX-04",
    uchastkId: "UCH-04A",
    holat: "faol",
    samaradorlik: 88,
    harorat: 900,
    bosim: 2.7,
    quvvat: 540,
    ishVaqti: 6840,
    keyingiTA: 150,
    model: "RM-650H",
    ishlab: "2015",
    imgUrl: "/images/uskunalar/prokat.svg",
  },
  {
    id: "USK-009",
    nom: "Gidravlik Nasos №3",
    tur: "Nasos",
    sexId: "SEX-05",
    uchastkId: "UCH-05A",
    holat: "xato",
    samaradorlik: 0,
    harorat: 90,
    bosim: 0,
    quvvat: 0,
    ishVaqti: 4120,
    keyingiTA: 0,
    model: "HP-450X",
    ishlab: "2017",
    imgUrl: "/images/uskunalar/nasos.svg",
  },
  {
    id: "USK-010",
    nom: "Kran №4",
    tur: "Kran",
    sexId: "SEX-05",
    uchastkId: "UCH-05C",
    holat: "faol",
    samaradorlik: 100,
    harorat: 28,
    bosim: 0,
    quvvat: 180,
    ishVaqti: 8400,
    keyingiTA: 200,
    model: "CR-50T",
    ishlab: "2014",
    imgUrl: "/images/uskunalar/kran.svg",
  },
  {
    id: "USK-011",
    nom: "Sovutish Nasoси №1",
    tur: "Nasos",
    sexId: "SEX-04",
    uchastkId: "UCH-04C",
    holat: "faol",
    samaradorlik: 96,
    harorat: 45,
    bosim: 3.2,
    quvvat: 220,
    ishVaqti: 5200,
    keyingiTA: 300,
    model: "WP-200C",
    ishlab: "2019",
    imgUrl: "/images/uskunalar/nasos.svg",
  },
  {
    id: "USK-012",
    nom: "Kesish Stanogi №1",
    tur: "Kesish",
    sexId: "SEX-04",
    uchastkId: "UCH-04D",
    holat: "faol",
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
    imgUrl: "/images/uskunalar/kesish.svg",
  },
  {
    id: "USK-013",
    nom: "Ko‘prikli kran №1",
    tur: "Kran",
    sexId: "SEX-07",
    uchastkId: "UCH-07A",
    holat: "faol",
    quvvat: 180,
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },
  {
    id: "USK-014",
    nom: "Ko‘prikli kran №2",
    tur: "Kran",
    sexId: "SEX-07",
    uchastkId: "UCH-07A",
    holat: "faol",
    quvvat: 180,
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },
  {
    id: "USK-015",
    nom: "Slab transport rolgangi",
    tur: "Transport",
    sexId: "SEX-07",
    uchastkId: "UCH-07A",
    holat: "faol",
    quvvat: 220,
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },
  {
    id: "USK-016",
    nom: "Slab markalash tizimi",
    tur: "Sensor",
    sexId: "SEX-07",
    uchastkId: "UCH-07A",
    holat: "faol",
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },

  {
    id: "USK-017",
    nom: "Metodik qizdirish pechi №1",
    tur: "Pech",
    sexId: "SEX-07",
    uchastkId: "UCH-07B",
    holat: "faol",
    quvvat: 950,
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },
  {
    id: "USK-018",
    nom: "Metodik qizdirish pechi №2",
    tur: "Pech",
    sexId: "SEX-07",
    uchastkId: "UCH-07B",
    holat: "faol",
    quvvat: 950,
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },
  {
    id: "USK-019",
    nom: "Pech yuklash manipulyatori",
    tur: "Manipulator",
    sexId: "SEX-07",
    uchastkId: "UCH-07B",
    holat: "faol",
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },

  {
    id: "USK-020",
    nom: "Roughing mill stani №1",
    tur: "Prokat",
    sexId: "SEX-07",
    uchastkId: "UCH-07C",
    holat: "faol",
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },
  {
    id: "USK-021",
    nom: "Roughing mill stani №2",
    tur: "Prokat",
    sexId: "SEX-07",
    uchastkId: "UCH-07C",
    holat: "faol",
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },
  {
    id: "USK-022",
    nom: "Gidravlik press",
    tur: "Press",
    sexId: "SEX-07",
    uchastkId: "UCH-07C",
    holat: "faol",
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },
  {
    id: "USK-023",
    nom: "Prokat rolgang liniyasi",
    tur: "Transport",
    sexId: "SEX-07",
    uchastkId: "UCH-07C",
    holat: "faol",
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },

  {
    id: "USK-024",
    nom: "Finishing mill stani №1",
    tur: "Prokat",
    sexId: "SEX-07",
    uchastkId: "UCH-07D",
    holat: "faol",
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },
  {
    id: "USK-025",
    nom: "Finishing mill stani №2",
    tur: "Prokat",
    sexId: "SEX-07",
    uchastkId: "UCH-07D",
    holat: "faol",
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },
  {
    id: "USK-026",
    nom: "Avtomatik qalinlik nazorati",
    tur: "Sensor",
    sexId: "SEX-07",
    uchastkId: "UCH-07D",
    holat: "faol",
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },

  {
    id: "USK-027",
    nom: "Cooling bed",
    tur: "Sovitish",
    sexId: "SEX-07",
    uchastkId: "UCH-07E",
    holat: "faol",
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },
  {
    id: "USK-028",
    nom: "List tekislash mashinasi",
    tur: "Tekislash",
    sexId: "SEX-07",
    uchastkId: "UCH-07E",
    samaradorlik: 94,
    holat: "faol",
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },

  {
    id: "USK-029",
    nom: "List kesish qaychilari",
    tur: "Kesish",
    sexId: "SEX-07",
    uchastkId: "UCH-07F",
    holat: "faol",
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },
  {
    id: "USK-030",
    nom: "List paketlash liniyasi",
    tur: "Qadoqlash",
    sexId: "SEX-07",
    uchastkId: "UCH-07F",
    holat: "faol",
    samaradorlik: 94,
    harorat: 120,
    bosim: 1.8,
    quvvat: 340,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "CS-1200",
    ishlab: "2021",
  },
  {
    id: "USK-031",
    nom: "Sirt tozalash liniyasi",
    tur: "Tozalash",
    sexId: "SEX-08",
    uchastkId: "UCH-08A",
    holat: "faol",
    samaradorlik: 88,
    harorat: 40,
    bosim: 1.2,
    quvvat: 120,
    ishVaqti: 4200,
    keyingiTA: 120,
    model: "CL-400",
    ishlab: "2020",
  },
  {
    id: "USK-032",
    nom: "Gruntlash purkagich",
    tur: "Bo‘yoq",
    sexId: "SEX-08",
    uchastkId: "UCH-08B",
    holat: "faol",
    samaradorlik: 82,
    harorat: 90,
    bosim: 1.8,
    quvvat: 80,
    ishVaqti: 3800,
    keyingiTA: 90,
    model: "PR-200",
    ishlab: "2021",
  },
  {
    id: "USK-033",
    nom: "Avtomatik emal qoplash roboti",
    tur: "Robot",
    sexId: "SEX-08",
    uchastkId: "UCH-08C",
    holat: "ogohlantirish",
    samaradorlik: 76,
    harorat: 160,
    bosim: 2.4,
    quvvat: 150,
    ishVaqti: 5100,
    keyingiTA: 30,
    model: "ER-600",
    ishlab: "2022",
  },
  {
    id: "USK-034",
    nom: "Quritish pechi №1",
    tur: "Pech",
    sexId: "SEX-08",
    uchastkId: "UCH-08D",
    holat: "faol",
    samaradorlik: 85,
    harorat: 180,
    bosim: 2.0,
    quvvat: 300,
    ishVaqti: 6200,
    keyingiTA: 60,
    model: "DR-800",
    ishlab: "2019",
  },
  {
    id: "USK-040",
    nom: "Induksion eritish pechi №1",
    tur: "Pech",
    sexId: "SEX-09",
    uchastkId: "UCH-09B",
    holat: "faol",
    samaradorlik: 82,
    harorat: 980,
    bosim: 2.8,
    quvvat: 600,
    ishVaqti: 5400,
    keyingiTA: 60,
    model: "IF-800",
    ishlab: "2021",
  },
  {
    id: "USK-041",
    nom: "Induksion eritish pechi №2",
    tur: "Pech",
    sexId: "SEX-09",
    uchastkId: "UCH-09B",
    holat: "faol",
    samaradorlik: 84,
    harorat: 970,
    bosim: 2.7,
    quvvat: 580,
    ishVaqti: 5100,
    keyingiTA: 45,
    model: "IF-800",
    ishlab: "2022",
  },
  {
    id: "USK-042",
    nom: "Avtomatik quyish mashinasi",
    tur: "Quyish",
    sexId: "SEX-09",
    uchastkId: "UCH-09C",
    holat: "ogohlantirish",
    samaradorlik: 74,
    harorat: 860,
    bosim: 2.2,
    quvvat: 300,
    ishVaqti: 4200,
    keyingiTA: 20,
    model: "CM-500",
    ishlab: "2020",
  },
  {
    id: "USK-043",
    nom: "Prokat stani (rangli metall)",
    tur: "Prokat",
    sexId: "SEX-09",
    uchastkId: "UCH-09D",
    holat: "faol",
    samaradorlik: 89,
    harorat: 420,
    bosim: 1.9,
    quvvat: 450,
    ishVaqti: 6100,
    keyingiTA: 120,
    model: "RM-400",
    ishlab: "2019",
  },
  {
    id: "USK-044",
    nom: "Sovutish vannasi",
    tur: "Sovitish",
    sexId: "SEX-09",
    uchastkId: "UCH-09E",
    holat: "faol",
    samaradorlik: 93,
    harorat: 80,
    bosim: 0.8,
    quvvat: 120,
    ishVaqti: 3000,
    keyingiTA: 200,
    model: "CB-200",
    ishlab: "2021",
  },
  {
    id: "USK-045",
    nom: "Spektr analizatori",
    tur: "Sensor",
    sexId: "SEX-09",
    uchastkId: "UCH-09E",
    holat: "faol",
    samaradorlik: 96,
    harorat: 35,
    bosim: 0,
    quvvat: 60,
    ishVaqti: 2800,
    keyingiTA: 365,
    model: "SA-900",
    ishlab: "2023",
  },
];

export const datchikData = [
  {
    id: "DATC-001",
    nom: "Harorat-01",
    tur: "harorat",
    sexId: "SEX-01",
    uchastkId: "UCH-01A",
    holat: "faol",
    qiymat: 1480,
    birlik: "°C",
    min: 800,
    max: 1600,
    chegara: 1550,
  },
  {
    id: "DATC-002",
    nom: "Harorat-02",
    tur: "harorat",
    sexId: "SEX-01",
    uchastkId: "UCH-01B",
    holat: "faol",
    qiymat: 1350,
    birlik: "°C",
    min: 800,
    max: 1600,
    chegara: 1550,
  },
  {
    id: "DATC-003",
    nom: "Bosim-01",
    tur: "bosim",
    sexId: "SEX-01",
    uchastkId: "UCH-01A",
    holat: "faol",
    qiymat: 4.2,
    birlik: "bar",
    min: 0,
    max: 10,
    chegara: 9,
  },
  {
    id: "DATC-034",
    nom: "Gaz-01",
    tur: "gaz",
    sexId: "SEX-03",
    uchastkId: "UCH-03A",
    holat: "ogohlantirish",
    qiymat: 8.3,
    birlik: "bar",
    min: 0,
    max: 10,
    chegara: 8.0,
  },
  {
    id: "DATC-056",
    nom: "Quvvat-01",
    tur: "quvvat",
    sexId: "SEX-03",
    uchastkId: "UCH-03C",
    holat: "faol",
    qiymat: 420,
    birlik: "kW",
    min: 0,
    max: 650,
    chegara: 600,
  },
  {
    id: "DATC-078",
    nom: "Oqim-01",
    tur: "oqim",
    sexId: "SEX-04",
    uchastkId: "UCH-04C",
    holat: "faol",
    qiymat: 240,
    birlik: "L/min",
    min: 0,
    max: 500,
    chegara: 450,
  },
  {
    id: "DATC-089",
    nom: "Bosim-02",
    tur: "bosim",
    sexId: "SEX-02",
    uchastkId: "UCH-02E",
    holat: "xato",
    qiymat: null,
    birlik: "bar",
    min: 0,
    max: 10,
    chegara: 9,
  },
  {
    id: "DATC-091",
    nom: "Tebranish-01",
    tur: "tebranish",
    sexId: "SEX-02",
    uchastkId: "UCH-02A",
    holat: "faol",
    qiymat: 0.8,
    birlik: "mm/s",
    min: 0,
    max: 5,
    chegara: 3.5,
  },
  {
    id: "DATC-012",
    nom: "Harorat-03",
    tur: "harorat",
    sexId: "SEX-02",
    uchastkId: "UCH-02A",
    holat: "faol",
    qiymat: 1620,
    birlik: "°C",
    min: 800,
    max: 1700,
    chegara: 1680,
  },
  {
    id: "DATC-045",
    nom: "Harorat-04",
    tur: "harorat",
    sexId: "SEX-04",
    uchastkId: "UCH-04A",
    holat: "faol",
    qiymat: 920,
    birlik: "°C",
    min: 400,
    max: 1200,
    chegara: 1100,
  },
  {
    id: "DATC-067",
    nom: "Oqim-02",
    tur: "oqim",
    sexId: "SEX-01",
    uchastkId: "UCH-01C",
    holat: "faol",
    qiymat: 180,
    birlik: "L/min",
    min: 0,
    max: 300,
    chegara: 280,
  },
  {
    id: "DATC-099",
    nom: "CO2-01",
    tur: "gaz",
    sexId: "SEX-03",
    uchastkId: "UCH-03A",
    holat: "faol",
    qiymat: 340,
    birlik: "ppm",
    min: 0,
    max: 500,
    chegara: 450,
  },
];

export const ogohlantirishlarData = [
  {
    id: "OG-001",
    daraja: "kritik",
    xabar: "Gidravlik nasos to'liq nosozligi aniqlandi",
    sex: "SEX-05",
    uchastka: "UCH-05A",
    uskuna: "USK-009",
    vaqt: new Date(Date.now() - 8 * 60000).toISOString(),
    holat: "ochiq",
    operator: "Karimov A.",
  },
  {
    id: "OG-002",
    daraja: "ogohlantirish",
    xabar: "Elektr pech №2 harorati chegaradan oshdi (1380°C > 1350°C)",
    sex: "SEX-03",
    uchastka: "UCH-03A",
    uskuna: "USK-006",
    vaqt: new Date(Date.now() - 24 * 60000).toISOString(),
    holat: "ochiq",
    operator: null,
  },
  {
    id: "OG-003",
    daraja: "ogohlantirish",
    xabar: "DATC-089 bosim datchigi signal bermayapti",
    sex: "SEX-02",
    uchastka: "UCH-02E",
    uskuna: null,
    vaqt: new Date(Date.now() - 41 * 60000).toISOString(),
    holat: "ko'rib chiqilmoqda",
    operator: "Toshmatov B.",
  },
  {
    id: "OG-004",
    daraja: "axborot",
    xabar: "Konverter №1 profilaktika muddati 30 kun qoldi",
    sex: "SEX-02",
    uchastka: "UCH-02A",
    uskuna: "USK-003",
    vaqt: new Date(Date.now() - 2 * 3600000).toISOString(),
    holat: "ochiq",
    operator: null,
  },
  {
    id: "OG-005",
    daraja: "axborot",
    xabar: "II-Smena ishga boshladi",
    sex: "BARCHASI",
    uchastka: null,
    uskuna: null,
    vaqt: new Date(Date.now() - 4 * 3600000).toISOString(),
    holat: "yopiq",
    operator: "Tizim",
  },
  {
    id: "OG-006",
    daraja: "ogohlantirish",
    xabar: "Gaz bosimi normal chegaradan oshdi (8.3 bar > 8.0 bar)",
    sex: "SEX-03",
    uchastka: "UCH-02E",
    uskuna: null,
    vaqt: new Date(Date.now() - 55 * 60000).toISOString(),
    holat: "ko'rib chiqilmoqda",
    operator: "Yusupov S.",
  },
  {
    id: "OG-007",
    daraja: "kritik",
    xabar: "Quyish sexi №5 to'xtatildi — texnik nosozlik",
    sex: "SEX-05",
    uchastka: "UCH-05A",
    uskuna: "USK-009",
    vaqt: new Date(Date.now() - 10 * 60000).toISOString(),
    holat: "ochiq",
    operator: "Karimov A.",
  },
];

// export const kameraData1 = [
//   {
//     id: "CAM-01",
//     nom: "Domna №1 Kirish",
//     sex: "SEX-01",
//     uchastka: "UCH-01A",
//     holat: "jonli",
//     rang: "#ff6b1a33",
//     emoji: "🔥",
//     fps: 25,
//   },
//   {
//     id: "CAM-02",
//     nom: "Elektr Pech №2",
//     sex: "SEX-03",
//     uchastka: "UCH-03A",
//     holat: "jonli",
//     rang: "#00d4ff22",
//     emoji: "⚡",
//     fps: 25,
//   },
//   {
//     id: "CAM-03",
//     nom: "Konverter Maydon",
//     sex: "SEX-02",
//     uchastka: "UCH-02A",
//     holat: "jonli",
//     rang: "#ff6b1a22",
//     emoji: "⚙️",
//     fps: 30,
//   },
//   {
//     id: "CAM-04",
//     nom: "Prokatlash Liniyasi",
//     sex: "SEX-04",
//     uchastka: "UCH-04A",
//     holat: "jonli",
//     rang: "#00ff9d11",
//     emoji: "🔄",
//     fps: 25,
//   },
//   {
//     id: "CAM-05",
//     nom: "Quyish Sexi",
//     sex: "SEX-05",
//     uchastka: "UCH-05A",
//     holat: "xato",
//     rang: "#ff2d5511",
//     emoji: "🏗️",
//     fps: 0,
//   },
//   {
//     id: "CAM-06",
//     nom: "Mexanik Sex Kirish",
//     sex: "SEX-06",
//     uchastka: "UCH-06A",
//     holat: "signal_yoq",
//     rang: "#ffffff05",
//     emoji: "📷",
//     fps: 0,
//   },
//   {
//     id: "CAM-07",
//     nom: "Domna №2 Yon",
//     sex: "SEX-01",
//     uchastka: "UCH-01B",
//     holat: "jonli",
//     rang: "#ff6b1a33",
//     emoji: "🔥",
//     fps: 25,
//   },
//   {
//     id: "CAM-08",
//     nom: "Sovutish Zonasi",
//     sex: "SEX-04",
//     uchastka: "UCH-04C",
//     holat: "jonli",
//     rang: "#00d4ff22",
//     emoji: "💧",
//     fps: 25,
//   },
//   {
//     id: "CAM-09",
//     nom: "Kesish Stansiyasi",
//     sex: "SEX-04",
//     uchastka: "UCH-04D",
//     holat: "jonli",
//     rang: "#00ff9d11",
//     emoji: "✂️",
//     fps: 30,
//   },
// ];

export const kameraData = [
  {
    id: 1,
    nom: "Domna №1 Kirish",
    sex: "SEX-01",
    uchastka: "UCH-01A",
    holat: "jonli",
    fps: 25,
    channel: 1,
  },
  {
    id: 2,
    nom: "Elektr Pech №2",
    sex: "SEX-03",
    uchastka: "UCH-03A",
    holat: "jonli",
    fps: 25,
    channel: 2,
  },
  {
    id: 3,
    nom: "Elektr Pech №2",
    sex: "SEX-03",
    uchastka: "UCH-03A",
    holat: "jonli",
    fps: 25,
    channel: 3,
  },
  {
    id: 4,
    nom: "Elektr Pech №2",
    sex: "SEX-03",
    uchastka: "UCH-03A",
    holat: "jonli",
    fps: 25,
    channel: 4,
  },
  {
    id: 5,
    nom: "Elektr Pech №2",
    sex: "SEX-03",
    uchastka: "UCH-03A",
    holat: "jonli",
    fps: 25,
    channel: 5,
  },
  {
    id: 6,
    nom: "Elektr Pech №2",
    sex: "SEX-03",
    uchastka: "UCH-03A",
    holat: "jonli",
    fps: 25,
    channel: 6,
  },
  {
    id: 7,
    nom: "Elektr Pech №2",
    sex: "SEX-03",
    uchastka: "UCH-03A",
    holat: "jonli",
    fps: 25,
    channel: 7,
  },
  {
    id: 8,
    nom: "Elektr Pech №2",
    sex: "SEX-03",
    uchastka: "UCH-03A",
    holat: "jonli",
    fps: 25,
    channel: 8,
  },
  {
    id: 9,
    nom: "Elektr Pech №2",
    sex: "SEX-03",
    uchastka: "UCH-03A",
    holat: "jonli",
    fps: 25,
    channel: 9,
  },
  {
    id: 10,
    nom: "Elektr Pech №2",
    sex: "SEX-03",
    uchastka: "UCH-03A",
    holat: "jonli",
    fps: 25,
    channel: 10,
  },
  {
    id: 11,
    nom: "Elektr Pech №2",
    sex: "SEX-03",
    uchastka: "UCH-03A",
    holat: "jonli",
    fps: 25,
    channel: 11,
  },
  {
    id: 12,
    nom: "Elektr Pech №2",
    sex: "SEX-03",
    uchastka: "UCH-03A",
    holat: "jonli",
    fps: 25,
    channel: 12,
  },
];

export const kpiData = {
  ishlab_chiqarish: 847,
  faol_uskunalar: 38,
  jami_uskunalar: 42,
  orta_harorat: 1240,
  faol_datchiklar: 139,
  jami_datchiklar: 142,
  energiya: 2840,
  ogohlantirishlar: 3,
};

export const haroratGrafik = Array.from({ length: 24 }, (_, i) => ({
  soat: `${String(i).padStart(2, "0")}:00`,
  domna: Math.round(1430 + Math.sin(i * 0.4) * 60 + Math.random() * 30),
  konverter: Math.round(1560 + Math.sin(i * 0.3 + 1) * 80 + Math.random() * 40),
  pech: Math.round(1300 + Math.sin(i * 0.5 + 2) * 50 + Math.random() * 20),
}));

export const ishlab_chiqarish_grafik = Array.from({ length: 7 }, (_, i) => {
  const sanalar = ["Du", "Se", "Ch", "Pa", "Ju", "Sh", "Ya"];
  return {
    kun: sanalar[i],
    choyan: Math.round(820 + Math.random() * 100),
    polat: Math.round(580 + Math.random() * 80),
    prokat: Math.round(380 + Math.random() * 80),
  };
});

// Simulate API with delay
export const apiDelay = (ms = 400) => new Promise((res) => setTimeout(res, ms));
