const latinToCyrillicRules = [
  [/G‘/g, "Ғ"],
  [/G'/g, "Ғ"],
  [/g‘/g, "ғ"],
  [/g'/g, "ғ"],
  [/O‘/g, "Ў"],
  [/O'/g, "Ў"],
  [/o‘/g, "ў"],
  [/o'/g, "ў"],
  [/Sh/g, "Ш"],
  [/sh/g, "ш"],
  [/Ch/g, "Ч"],
  [/ch/g, "ч"],
  [/Yo/g, "Ё"],
  [/yo/g, "ё"],
  [/Yu/g, "Ю"],
  [/yu/g, "ю"],
  [/Ya/g, "Я"],
  [/ya/g, "я"],
  [/A/g, "А"],
  [/a/g, "а"],
  [/B/g, "Б"],
  [/b/g, "б"],
  [/D/g, "Д"],
  [/d/g, "д"],
  [/E/g, "Е"],
  [/e/g, "е"],
  [/F/g, "Ф"],
  [/f/g, "ф"],
  [/G/g, "Г"],
  [/g/g, "г"],
  [/H/g, "Ҳ"],
  [/h/g, "ҳ"],
  [/I/g, "И"],
  [/i/g, "и"],
  [/J/g, "Ж"],
  [/j/g, "ж"],
  [/K/g, "К"],
  [/k/g, "к"],
  [/L/g, "Л"],
  [/l/g, "л"],
  [/M/g, "М"],
  [/m/g, "м"],
  [/N/g, "Н"],
  [/n/g, "н"],
  [/O/g, "О"],
  [/o/g, "о"],
  [/P/g, "П"],
  [/p/g, "п"],
  [/Q/g, "Қ"],
  [/q/g, "қ"],
  [/R/g, "Р"],
  [/r/g, "р"],
  [/S/g, "С"],
  [/s/g, "с"],
  [/T/g, "Т"],
  [/t/g, "т"],
  [/U/g, "У"],
  [/u/g, "у"],
  [/V/g, "В"],
  [/v/g, "в"],
  [/X/g, "Х"],
  [/x/g, "х"],
  [/Y/g, "Й"],
  [/y/g, "й"],
  [/Z/g, "З"],
  [/z/g, "з"],
  [/'/g, "ъ"],
];

export function latinToCyrillic(text = "") {
  let result = String(text);
  for (const [pattern, value] of latinToCyrillicRules) {
    result = result.replace(pattern, value);
  }
  return result;
}
